### ISSUE TITLE
Nifti support

### ISSUE THREAD

**Issue by tom1193** [reginabarzilaygroup/Sybil#12]
Hi,
Thank you for publishing this tool. I have code extending support for nifti files at https://github.com/tom1193/Sybil/tree/nifti-wrapper. I tested on the Ardila test set using dcm2niix to generate nifti files. Risk scores on the scan level are quite different (<0.1) b/w the two formats. Differences in aggregate AUC on the test set are not as bad (<0.01). I'm happy to submit a PR if you would like to add this feature and think it's "close enough". Also open to suggestions that could account for these differences in risk scores.

**Comment by pgmikhael** [comment]
Hi! 

Thanks for contributing!! 

Any idea why the risk scores would be different? Is there a way to achieve parity between the two inputs before passing them through model (we had done that for PNG and DICOM for instance)? If so, that would be ideal.

**Comment by tom1193** [comment]
I implemented a [3d scale augmentation](https://github.com/tom1193/Sybil/blob/92746d019c77cd76f7c1de084e92f19644412a0a/sybil/augmentations.py#L131) analogous to the 2d scale. This is causing inputs to be different, assuming parity before augmentation. There is parity before augmentations for the one scan I looked at, but I didn't explicitly check the entire dataset. Looking into it!

**Comment by jsilter** [comment]
I don't think this file format is widely used for LDCT. Happy to re-open if there is additional demand, but for now I'm closing this issue.
