### ISSUE TITLE
Dataset split

### ISSUE THREAD

**Issue by giurdeluca** [reginabarzilaygroup/Sybil#17]
Hi,
firstly, I want to express my appreciation for the valuable tool you've shared with the community!
In the Data Sharing Statement of your work it says that the data splits, along with expert radiologist annotations, trained models, and code are available in this repo. However, I cannot find the data split, and it seems that the files uploaded [here](https://github.com/reginabarzilaygroup/Sybil/tree/main/files) are empty.
Could you please provide the missing data split?
Thank you

**Comment by pgmikhael** [comment]
Hi!

The data / model files are stored [here](https://drive.google.com/drive/folders/1nBp05VV9mf5CfEO6W5RY4ZpcpxmPDEeR?usp=sharing) -- this is in the README but probably not very clearly marked.

**Comment by giurdeluca** [comment]
Sorry for the overlook then and thank you for the prompt response
