### ISSUE TITLE
SCORE meaning

### ISSUE THREAD

**Issue by jhchenchong** [reginabarzilaygroup/Sybil#18]
I am a beginner. I got the Prediction scores and I want to know what each score represents
Prediction(scores=[[0.0005993253234549188, 0.0032729617776346745, 0.005461805129414722, 0.010187651898493539, 0.01629524016091344, 0.027880663449820757], [0.002614143679095454, 0.006778430365650433, 0.01608498481612357, 0.02285970665741425, 0.027484834813507393, 0.0459973147267193]])
Thanks!

**Comment by pgmikhael** [comment]
Hi, these look to be scores for two exams. For each exam, there are 6 scores that correspond to the predicted probability of cancer development within X years. For instance, the second score in each list is the predicted probability of cancer development within 2 years. These are calibrated to the population that the model was trained on.
