### ISSUE TITLE
(preprocessing) When the data volumes were resampled to 0.7*0.7*2.5 mm3 voxels, is there a standard width and height of pixels for all the volumes?

### ISSUE THREAD

**Issue by ZiyangLiu** [reginabarzilaygroup/Sybil#19]
Hello. I am studying your paper and your code and I have a question about your preprocessing. 

In your paper's Supplementary Methods, it mentioned that the data volumes were resampled to 0.7 * 0.7 * 2.5 mm3 voxels and then the width and height were resized to 256*256 pixels. 
When the data volumes were resampled to 0.7 * 0.7 * 2.5 mm3 voxels, is there a standard width and height of pixels for all the volumes? (the volumes' depth is 200, as mentioned in the paper)

(If different data volumes have different width and height of pixels after they are resampled to 0.7 * 0.7 * 2.5 mm3 voxels, the resampling doesn't make sense when the data volumes are resized to 256*256 pixels because the voxels of different data volumes will have different sizes after the resizing.)

Thank you very much.

**Comment by pgmikhael** [comment]
Hi!

Yes, the LDCTs came as 512x512 pixel arrays.
