### ISSUE TITLE
question about the bounding box annotations

### ISSUE THREAD

**Issue by deepakri201** [reginabarzilaygroup/Sybil#21]
Hi, 

My team and I at BWH (@fedorov) are interested in using your expert bounding box annotations, and are currently trying to display them in 3DSlicer. 

Here I've chosen a particular annotation to display: 

	"1.2.840.113654.2.55.56880820416622279507487194633461962174": {
		"1.2.840.113654.2.55.133415818681717538807299664091449063309": [
			{
				"x": 0.43682755859375,
				"y": 0.2967157421875,
				"width": 0.30124578125,
				"height": 0.20271802734375
			}
		],

After converting the top left, bottom right, and center coordinates to mm space, we have the following in Slicer: 

![image](https://github.com/reginabarzilaygroup/Sybil/assets/59979551/8d2ffd0e-6abe-4b1e-81ab-9a371ae57674)

However, this bounding box almost looks too large for the nodule in question. 

We wanted to make sure that the above annotation annotation is correct, and that the bounding box corresponds to the original DICOM data. Did the experts use any guidelines to define the bounding boxes around the nodules? (for instance a set margin of 10 voxels around the nodule). 

Thank you! 

Deepa

**Comment by pgmikhael** [comment]
Hi,

Thanks for reaching out! I took a look, and it looks like your reconstruction of the bounding is correct. It does look big but it's certainly consistent with what I got. Dr. Florian Fintelmann (senior author on the publication) led the annotation efforts and would have more details on the actual process ([fintelmann@mgh.harvard.edu](mailto:mailto:fintelmann@mgh.harvard.edu)).
