### ISSUE TITLE
Attribution for NLST dataset

### ISSUE THREAD

**Issue by kirbyju** [reginabarzilaygroup/Sybil#40]
Hi, it's great to see you all leveraging the National Lung Screening Trial dataset.  Can you please add the dataset citation to your README.md in order to adhere to TCIA's Data Usage and Citation Policy?

`National Lung Screening Trial Research Team. (2013). Data from the National Lung Screening Trial (NLST) [Data set]. The Cancer Imaging Archive. https://doi.org/10.7937/TCIA.HMQ8-J677`

Also, if you'd like to increase awareness of your data and code you might consider submitting a proposal to publish the annotations as described in https://www.cancerimagingarchive.net/analysis-results/ or adding your data to https://zenodo.org/communities/nci-idc/about (which would also result in us linking to your dataset on the NLST page).

Best,
Justin

**Comment by pgmikhael** [comment]
Hi Justin,

Thanks for reaching out. Yes, will add the citation -- the data we used was obtained as a hard drive from [CDAS](https://cdas.cancer.gov/nlst/) rather from the archive but not sure there's a meaningful difference. 

Thanks for bringing the possibility of submitting the annotations to our attention!

**Comment by jsilter** [comment]
Citation added to README
