### ISSUE TITLE
Training Sybil 

### ISSUE THREAD

**Issue by Malaikah-Javed** [reginabarzilaygroup/Sybil#50]
How are the images fed for training?  
If NLST contains 3D dicom of each patient,  then how is each 2D image of each patient fed into the code?
Is there a specific way to give the path to the images?

**Comment by pgmikhael** [comment]
Hi,

The series of 2D images are concatenated into a 3D tensor that is fed to the model. Please refer to the [dataset file](https://github.com/reginabarzilaygroup/Sybil/blob/main/sybil/datasets/nlst.py) for details on processing and preparing the input.
