### ISSUE TITLE
ValueError: high is out of bounds for int32

### ISSUE THREAD

**Issue by jryoungw** [reginabarzilaygroup/Sybil#8]
### Error message
ValueError: high is out of bounds for int32
### Solution
modify 132-th line of `sybil/serie.py` as follows:
`sample = {"seed": np.random.randint(0, 2**32 - 1)}`
to
`sample = {"seed": np.random.randint(0, 2**32 - 1, dtype=np.int64)}`

**Comment by max-bacon** [comment]
I second this.

**Comment by max-bacon** [comment]
Even with that change, there are still other issues. This seems to be a Windows-only problem and doesn't occur on other OS.

**Comment by pgmikhael** [comment]
In case this is helpful to others, if this is a Windows issue, then there is a Windows-supported docker image released (https://github.com/reginabarzilaygroup/Sybil/wiki).
